### ISSUE TITLE
Plan out the main parts our project will need

### ISSUE THREAD

**Issue by Dustin-Klein** [Staley-Robotics/StaleyRC2020#17]
Create a file, call it STRUCTURE.md or something and layout the different components of our project.

Break our robot off into subsections and describe the components.

 - Subsystem
   - hardware used
     - sensors
     - speed controllers
   - important methods in the subsystem
 - Commands

**Comment by SHS-Programmers** [comment]
done diddly done. called Structure.md

**Comment by Dustin-Klein** [comment]
@ryanperrycarlson You forgot to put in the feeder commands.  Also I think shifting can be moved to a drive command.

**Comment by bobtheragelot** [comment]
@ryanperrycarlson Elaborate on why we are using omniwheels, also update the sensor since we are no longer using it. 
Move run1ball down to the other shooter commands.
Add method stopWinch
Expand on what color spin and numberSpin actually entail.

**Comment by SHS-Programmers** [comment]
The structure MD file has been updated.
